import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import LandingMain from '../components/LandingMain'
import { useState } from 'react'
export default function Home() {
  return (


      <header className={styles.header}>
      <Head>
        <title>Space tourism</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" /> 
        <link href="https://fonts.googleapis.com/css2?family=Bellefair&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Barlow&display=swap" rel="stylesheet" />
      </Head>
        <div className={styles.gap}></div>
        <div className={styles.bodyWrap}>
        <LandingMain />
        </div>
      </header>
  
  )
}
